// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjspspfarntsxfcrrgdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqc3BzcGZhcm50c3hmY3JyZ2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODEyMTIsImV4cCI6MjA3Mzk1NzIxMn0.XqXqyXLZCu7453Ice6W7WQ5rnfUUaHRa1fGkbR05VNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});